---
- name: setup nginx for sonar qube
  hosts: ub02
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ../../vars/sonar_vars.yaml
  tasks:

    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: removing nginx default directories
      shell: |
        rm -rf /etc/nginx/sites-enabled/default
        rm -rf /etc/nginx/sites-available/default

    - name: configure nginx for sonarqube
      copy:
        dest: /etc/nginx/sites-available/sonarqube
        content: |
          server {
              listen 80;
              server_name {{ domain_name }};

              access_log  /var/log/nginx/sonar.access.log;
              error_log   /var/log/nginx/sonar.error.log;

              proxy_buffers 16 64k;
              proxy_buffer_size 128k;

              location / {
                  proxy_pass  http://127.0.0.1:{{ sonar_web_port }};
                  proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
                  proxy_redirect off;

                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto http;
              }
          }

    - name: enable nginx site
      file:
        src: /etc/nginx/sites-available/sonarqube
        dest: /etc/nginx/sites-enabled/sonarqube
        state: link
        force: yes

    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: allow firewall ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 80
        - 9000
        - 9001

    - name: Reboot system
      reboot:
        msg: "Rebooting after SonarQube setup"
        pre_reboot_delay: 30

